import { useQuery } from "@tanstack/react-query";
import { KeyRound, RefreshCw } from "lucide-react";
import { CodeTile } from "../components/CodeTile";
import { EmptyState } from "../components/EmptyState";
import { verificationsApi } from "../lib/api";
import { cn } from "../lib/utils";

export function OtpsPage() {
  const {
    data: verificationsData,
    isLoading,
    refetch,
    isRefetching,
  } = useQuery({
    queryKey: ["verifications"],
    queryFn: () => verificationsApi.list({ limit: 50 }),
  });

  const verifications = verificationsData?.verifications || [];

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-foreground tracking-tight">OTPs & Verifications</h2>
          <p className="text-xs text-muted-foreground mt-0.5">
            Active verification codes generated by the Verify API and extracted from incoming
            messages
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => refetch()}
            disabled={isRefetching}
            className="p-2 rounded-md border border-border bg-card text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            title="Refresh codes"
            aria-label="Refresh codes"
          >
            <RefreshCw className={cn("w-4 h-4", isRefetching && "animate-spin")} />
          </button>
        </div>
      </div>

      {/* Grid of OTPs */}
      {verifications.length === 0 && !isLoading ? (
        <EmptyState
          icon={KeyRound}
          title="No Active Verification Codes"
          description="Verification codes generated by the Verify API or detected in messages will appear here as copyable code tiles."
          actionLabel="Refresh List"
          onAction={() => refetch()}
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {verifications.map((vrf) => {
            const isExpired = vrf.status === "expired";
            const isApproved = vrf.status === "approved";

            return (
              <div
                key={vrf.id}
                className="p-5 rounded-xl bg-card border border-border shadow-xs space-y-4 hover:border-ember-300 dark:hover:border-ember-800 transition-all"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-semibold text-foreground">
                      {vrf.to}
                    </span>
                  </div>

                  <span
                    className={cn(
                      "px-2 py-0.5 rounded-full text-[11px] font-medium uppercase font-mono",
                      isApproved
                        ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300"
                        : isExpired
                          ? "bg-neutral-100 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-400"
                          : "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300"
                    )}
                  >
                    {vrf.status}
                  </span>
                </div>

                {/* Large Code Tile */}
                <CodeTile code={vrf.code} size="large" source="Verify" />

                <div className="flex items-center justify-between text-[11px] text-muted-foreground pt-1 border-t border-border/60">
                  <span>
                    Attempts: {vrf.attempts} / {vrf.max_attempts}
                  </span>
                  <span className="font-mono tabular-nums">
                    {new Date(vrf.created_at).toLocaleTimeString()}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
