// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BatchChannel.
const (
	BatchChannelEmail BatchChannel = "email"
	BatchChannelSms   BatchChannel = "sms"
)

// Valid indicates whether the value is a known member of the BatchChannel enum.
func (e BatchChannel) Valid() bool {
	switch e {
	case BatchChannelEmail:
		return true
	case BatchChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for CheckVerificationResponseStatus.
const (
	CheckVerificationResponseStatusApproved    CheckVerificationResponseStatus = "approved"
	CheckVerificationResponseStatusCanceled    CheckVerificationResponseStatus = "canceled"
	CheckVerificationResponseStatusExpired     CheckVerificationResponseStatus = "expired"
	CheckVerificationResponseStatusMaxAttempts CheckVerificationResponseStatus = "max_attempts"
	CheckVerificationResponseStatusPending     CheckVerificationResponseStatus = "pending"
)

// Valid indicates whether the value is a known member of the CheckVerificationResponseStatus enum.
func (e CheckVerificationResponseStatus) Valid() bool {
	switch e {
	case CheckVerificationResponseStatusApproved:
		return true
	case CheckVerificationResponseStatusCanceled:
		return true
	case CheckVerificationResponseStatusExpired:
		return true
	case CheckVerificationResponseStatusMaxAttempts:
		return true
	case CheckVerificationResponseStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for MessageChannel.
const (
	MessageChannelEmail MessageChannel = "email"
	MessageChannelSms   MessageChannel = "sms"
)

// Valid indicates whether the value is a known member of the MessageChannel enum.
func (e MessageChannel) Valid() bool {
	switch e {
	case MessageChannelEmail:
		return true
	case MessageChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for MessageDirection.
const (
	MessageDirectionInbound  MessageDirection = "inbound"
	MessageDirectionOutbound MessageDirection = "outbound"
)

// Valid indicates whether the value is a known member of the MessageDirection enum.
func (e MessageDirection) Valid() bool {
	switch e {
	case MessageDirectionInbound:
		return true
	case MessageDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for MessageEncoding.
const (
	MessageEncodingGsm7 MessageEncoding = "gsm7"
	MessageEncodingUcs2 MessageEncoding = "ucs2"
)

// Valid indicates whether the value is a known member of the MessageEncoding enum.
func (e MessageEncoding) Valid() bool {
	switch e {
	case MessageEncodingGsm7:
		return true
	case MessageEncodingUcs2:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	MessageStatusDelivered   MessageStatus = "delivered"
	MessageStatusFailed      MessageStatus = "failed"
	MessageStatusQueued      MessageStatus = "queued"
	MessageStatusReceived    MessageStatus = "received"
	MessageStatusSent        MessageStatus = "sent"
	MessageStatusUndelivered MessageStatus = "undelivered"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusDelivered:
		return true
	case MessageStatusFailed:
		return true
	case MessageStatusQueued:
		return true
	case MessageStatusReceived:
		return true
	case MessageStatusSent:
		return true
	case MessageStatusUndelivered:
		return true
	default:
		return false
	}
}

// Defines values for MessageWithEventsChannel.
const (
	MessageWithEventsChannelEmail MessageWithEventsChannel = "email"
	MessageWithEventsChannelSms   MessageWithEventsChannel = "sms"
)

// Valid indicates whether the value is a known member of the MessageWithEventsChannel enum.
func (e MessageWithEventsChannel) Valid() bool {
	switch e {
	case MessageWithEventsChannelEmail:
		return true
	case MessageWithEventsChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for MessageWithEventsDirection.
const (
	MessageWithEventsDirectionInbound  MessageWithEventsDirection = "inbound"
	MessageWithEventsDirectionOutbound MessageWithEventsDirection = "outbound"
)

// Valid indicates whether the value is a known member of the MessageWithEventsDirection enum.
func (e MessageWithEventsDirection) Valid() bool {
	switch e {
	case MessageWithEventsDirectionInbound:
		return true
	case MessageWithEventsDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for MessageWithEventsEncoding.
const (
	MessageWithEventsEncodingGsm7 MessageWithEventsEncoding = "gsm7"
	MessageWithEventsEncodingUcs2 MessageWithEventsEncoding = "ucs2"
)

// Valid indicates whether the value is a known member of the MessageWithEventsEncoding enum.
func (e MessageWithEventsEncoding) Valid() bool {
	switch e {
	case MessageWithEventsEncodingGsm7:
		return true
	case MessageWithEventsEncodingUcs2:
		return true
	default:
		return false
	}
}

// Defines values for MessageWithEventsStatus.
const (
	MessageWithEventsStatusDelivered   MessageWithEventsStatus = "delivered"
	MessageWithEventsStatusFailed      MessageWithEventsStatus = "failed"
	MessageWithEventsStatusQueued      MessageWithEventsStatus = "queued"
	MessageWithEventsStatusReceived    MessageWithEventsStatus = "received"
	MessageWithEventsStatusSent        MessageWithEventsStatus = "sent"
	MessageWithEventsStatusUndelivered MessageWithEventsStatus = "undelivered"
)

// Valid indicates whether the value is a known member of the MessageWithEventsStatus enum.
func (e MessageWithEventsStatus) Valid() bool {
	switch e {
	case MessageWithEventsStatusDelivered:
		return true
	case MessageWithEventsStatusFailed:
		return true
	case MessageWithEventsStatusQueued:
		return true
	case MessageWithEventsStatusReceived:
		return true
	case MessageWithEventsStatusSent:
		return true
	case MessageWithEventsStatusUndelivered:
		return true
	default:
		return false
	}
}

// Defines values for OTPLatestResponseSource.
const (
	OTPLatestResponseSourceExtracted    OTPLatestResponseSource = "extracted"
	OTPLatestResponseSourceVerification OTPLatestResponseSource = "verification"
)

// Valid indicates whether the value is a known member of the OTPLatestResponseSource enum.
func (e OTPLatestResponseSource) Valid() bool {
	switch e {
	case OTPLatestResponseSourceExtracted:
		return true
	case OTPLatestResponseSourceVerification:
		return true
	default:
		return false
	}
}

// Defines values for StartVerificationRequestChannel.
const (
	StartVerificationRequestChannelEmail StartVerificationRequestChannel = "email"
	StartVerificationRequestChannelSms   StartVerificationRequestChannel = "sms"
)

// Valid indicates whether the value is a known member of the StartVerificationRequestChannel enum.
func (e StartVerificationRequestChannel) Valid() bool {
	switch e {
	case StartVerificationRequestChannelEmail:
		return true
	case StartVerificationRequestChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for StatusEventStatus.
const (
	StatusEventStatusDelivered   StatusEventStatus = "delivered"
	StatusEventStatusFailed      StatusEventStatus = "failed"
	StatusEventStatusQueued      StatusEventStatus = "queued"
	StatusEventStatusReceived    StatusEventStatus = "received"
	StatusEventStatusSent        StatusEventStatus = "sent"
	StatusEventStatusUndelivered StatusEventStatus = "undelivered"
)

// Valid indicates whether the value is a known member of the StatusEventStatus enum.
func (e StatusEventStatus) Valid() bool {
	switch e {
	case StatusEventStatusDelivered:
		return true
	case StatusEventStatusFailed:
		return true
	case StatusEventStatusQueued:
		return true
	case StatusEventStatusReceived:
		return true
	case StatusEventStatusSent:
		return true
	case StatusEventStatusUndelivered:
		return true
	default:
		return false
	}
}

// Defines values for VerificationChannel.
const (
	VerificationChannelEmail VerificationChannel = "email"
	VerificationChannelSms   VerificationChannel = "sms"
)

// Valid indicates whether the value is a known member of the VerificationChannel enum.
func (e VerificationChannel) Valid() bool {
	switch e {
	case VerificationChannelEmail:
		return true
	case VerificationChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for VerificationStatus.
const (
	VerificationStatusApproved    VerificationStatus = "approved"
	VerificationStatusCanceled    VerificationStatus = "canceled"
	VerificationStatusExpired     VerificationStatus = "expired"
	VerificationStatusMaxAttempts VerificationStatus = "max_attempts"
	VerificationStatusPending     VerificationStatus = "pending"
)

// Valid indicates whether the value is a known member of the VerificationStatus enum.
func (e VerificationStatus) Valid() bool {
	switch e {
	case VerificationStatusApproved:
		return true
	case VerificationStatusCanceled:
		return true
	case VerificationStatusExpired:
		return true
	case VerificationStatusMaxAttempts:
		return true
	case VerificationStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for WebhookDeliveryKind.
const (
	WebhookDeliveryKindInbound WebhookDeliveryKind = "inbound"
	WebhookDeliveryKindStatus  WebhookDeliveryKind = "status"
)

// Valid indicates whether the value is a known member of the WebhookDeliveryKind enum.
func (e WebhookDeliveryKind) Valid() bool {
	switch e {
	case WebhookDeliveryKindInbound:
		return true
	case WebhookDeliveryKindStatus:
		return true
	default:
		return false
	}
}

// Defines values for WebhookDeliveryStatus.
const (
	WebhookDeliveryStatusFailed    WebhookDeliveryStatus = "failed"
	WebhookDeliveryStatusPending   WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusSucceeded WebhookDeliveryStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the WebhookDeliveryStatus enum.
func (e WebhookDeliveryStatus) Valid() bool {
	switch e {
	case WebhookDeliveryStatusFailed:
		return true
	case WebhookDeliveryStatusPending:
		return true
	case WebhookDeliveryStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for Healthz200JSONResponseBodyStatus.
const (
	Ok Healthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the Healthz200JSONResponseBodyStatus enum.
func (e Healthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ListMessagesParamsChannel.
const (
	ListMessagesParamsChannelEmail ListMessagesParamsChannel = "email"
	ListMessagesParamsChannelSms   ListMessagesParamsChannel = "sms"
)

// Valid indicates whether the value is a known member of the ListMessagesParamsChannel enum.
func (e ListMessagesParamsChannel) Valid() bool {
	switch e {
	case ListMessagesParamsChannelEmail:
		return true
	case ListMessagesParamsChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for ListMessagesParamsStatus.
const (
	ListMessagesParamsStatusDelivered   ListMessagesParamsStatus = "delivered"
	ListMessagesParamsStatusFailed      ListMessagesParamsStatus = "failed"
	ListMessagesParamsStatusQueued      ListMessagesParamsStatus = "queued"
	ListMessagesParamsStatusReceived    ListMessagesParamsStatus = "received"
	ListMessagesParamsStatusSent        ListMessagesParamsStatus = "sent"
	ListMessagesParamsStatusUndelivered ListMessagesParamsStatus = "undelivered"
)

// Valid indicates whether the value is a known member of the ListMessagesParamsStatus enum.
func (e ListMessagesParamsStatus) Valid() bool {
	switch e {
	case ListMessagesParamsStatusDelivered:
		return true
	case ListMessagesParamsStatusFailed:
		return true
	case ListMessagesParamsStatusQueued:
		return true
	case ListMessagesParamsStatusReceived:
		return true
	case ListMessagesParamsStatusSent:
		return true
	case ListMessagesParamsStatusUndelivered:
		return true
	default:
		return false
	}
}

// Defines values for ListMessagesParamsDirection.
const (
	ListMessagesParamsDirectionInbound  ListMessagesParamsDirection = "inbound"
	ListMessagesParamsDirectionOutbound ListMessagesParamsDirection = "outbound"
)

// Valid indicates whether the value is a known member of the ListMessagesParamsDirection enum.
func (e ListMessagesParamsDirection) Valid() bool {
	switch e {
	case ListMessagesParamsDirectionInbound:
		return true
	case ListMessagesParamsDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for WaitForMessageParamsChannel.
const (
	WaitForMessageParamsChannelEmail WaitForMessageParamsChannel = "email"
	WaitForMessageParamsChannelSms   WaitForMessageParamsChannel = "sms"
)

// Valid indicates whether the value is a known member of the WaitForMessageParamsChannel enum.
func (e WaitForMessageParamsChannel) Valid() bool {
	switch e {
	case WaitForMessageParamsChannelEmail:
		return true
	case WaitForMessageParamsChannelSms:
		return true
	default:
		return false
	}
}

// AttachmentInput defines model for AttachmentInput.
type AttachmentInput struct {
	ContentBase64 []byte  `json:"content_base64"`
	ContentType   string  `json:"content_type"`
	Filename      string  `json:"filename"`
	InlineCid     *string `json:"inline_cid,omitempty"`
}

// Batch defines model for Batch.
type Batch struct {
	Channel   *BatchChannel   `json:"channel,omitempty"`
	Counts    *map[string]int `json:"counts,omitempty"`
	CreatedAt *time.Time      `json:"created_at,omitempty"`
	Id        *string         `json:"id,omitempty"`
	ProjectId *string         `json:"project_id,omitempty"`
	Provider  *string         `json:"provider,omitempty"`
	Total     *int            `json:"total,omitempty"`
}

// BatchChannel defines model for Batch.Channel.
type BatchChannel string

// CheckVerificationRequest defines model for CheckVerificationRequest.
type CheckVerificationRequest struct {
	Code string `json:"code"`
}

// CheckVerificationResponse defines model for CheckVerificationResponse.
type CheckVerificationResponse struct {
	Status CheckVerificationResponseStatus `json:"status"`
	Valid  bool                            `json:"valid"`
}

// CheckVerificationResponseStatus defines model for CheckVerificationResponse.Status.
type CheckVerificationResponseStatus string

// EmailLatestResponse defines model for EmailLatestResponse.
type EmailLatestResponse struct {
	Codes       []string `json:"codes"`
	Links       []string `json:"links"`
	Message     Message  `json:"message"`
	PrimaryLink string   `json:"primary_link"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		Code    string  `json:"code"`
		Field   *string `json:"field,omitempty"`
		Message string  `json:"message"`
	} `json:"error,omitempty"`
}

// InboundRequest defines model for InboundRequest.
type InboundRequest struct {
	Body string `json:"body"`
	From string `json:"from"`
	To   string `json:"to"`
}

// LinkCredentialRequest defines model for LinkCredentialRequest.
type LinkCredentialRequest struct {
	Key      string `json:"key"`
	Provider string `json:"provider"`
}

// Message defines model for Message.
type Message struct {
	BatchId        *string           `json:"batch_id,omitempty"`
	Bcc            *[]string         `json:"bcc,omitempty"`
	BodyHtml       *string           `json:"body_html,omitempty"`
	BodyText       *string           `json:"body_text,omitempty"`
	CallbackUrl    *string           `json:"callback_url,omitempty"`
	Cc             *[]string         `json:"cc,omitempty"`
	Channel        *MessageChannel   `json:"channel,omitempty"`
	CreatedAt      *time.Time        `json:"created_at,omitempty"`
	Direction      *MessageDirection `json:"direction,omitempty"`
	Encoding       *MessageEncoding  `json:"encoding,omitempty"`
	ErrorCode      *string           `json:"error_code,omitempty"`
	ErrorMessage   *string           `json:"error_message,omitempty"`
	ExtractedCodes *[]string         `json:"extracted_codes,omitempty"`
	ExtractedLinks *[]string         `json:"extracted_links,omitempty"`
	From           *string           `json:"from,omitempty"`
	Id             *string           `json:"id,omitempty"`
	PrimaryLink    *string           `json:"primary_link,omitempty"`
	ProjectId      *string           `json:"project_id,omitempty"`
	Provider       *string           `json:"provider,omitempty"`
	ProviderRef    *string           `json:"provider_ref,omitempty"`
	Segments       *int              `json:"segments,omitempty"`
	Status         *MessageStatus    `json:"status,omitempty"`
	Subject        *string           `json:"subject,omitempty"`
	To             *string           `json:"to,omitempty"`
	UpdatedAt      *time.Time        `json:"updated_at,omitempty"`
}

// MessageChannel defines model for Message.Channel.
type MessageChannel string

// MessageDirection defines model for Message.Direction.
type MessageDirection string

// MessageEncoding defines model for Message.Encoding.
type MessageEncoding string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// MessageListResponse defines model for MessageListResponse.
type MessageListResponse struct {
	Messages   *[]Message `json:"messages,omitempty"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// MessageWithEvents defines model for MessageWithEvents.
type MessageWithEvents struct {
	BatchId        *string                     `json:"batch_id,omitempty"`
	Bcc            *[]string                   `json:"bcc,omitempty"`
	BodyHtml       *string                     `json:"body_html,omitempty"`
	BodyText       *string                     `json:"body_text,omitempty"`
	CallbackUrl    *string                     `json:"callback_url,omitempty"`
	Cc             *[]string                   `json:"cc,omitempty"`
	Channel        *MessageWithEventsChannel   `json:"channel,omitempty"`
	CreatedAt      *time.Time                  `json:"created_at,omitempty"`
	Direction      *MessageWithEventsDirection `json:"direction,omitempty"`
	Encoding       *MessageWithEventsEncoding  `json:"encoding,omitempty"`
	ErrorCode      *string                     `json:"error_code,omitempty"`
	ErrorMessage   *string                     `json:"error_message,omitempty"`
	ExtractedCodes *[]string                   `json:"extracted_codes,omitempty"`
	ExtractedLinks *[]string                   `json:"extracted_links,omitempty"`
	From           *string                     `json:"from,omitempty"`
	Id             *string                     `json:"id,omitempty"`
	PrimaryLink    *string                     `json:"primary_link,omitempty"`
	ProjectId      *string                     `json:"project_id,omitempty"`
	Provider       *string                     `json:"provider,omitempty"`
	ProviderRef    *string                     `json:"provider_ref,omitempty"`
	Segments       *int                        `json:"segments,omitempty"`
	Status         *MessageWithEventsStatus    `json:"status,omitempty"`
	StatusEvents   *[]StatusEvent              `json:"status_events,omitempty"`
	Subject        *string                     `json:"subject,omitempty"`
	To             *string                     `json:"to,omitempty"`
	UpdatedAt      *time.Time                  `json:"updated_at,omitempty"`
}

// MessageWithEventsChannel defines model for MessageWithEvents.Channel.
type MessageWithEventsChannel string

// MessageWithEventsDirection defines model for MessageWithEvents.Direction.
type MessageWithEventsDirection string

// MessageWithEventsEncoding defines model for MessageWithEvents.Encoding.
type MessageWithEventsEncoding string

// MessageWithEventsStatus defines model for MessageWithEvents.Status.
type MessageWithEventsStatus string

// OTPLatestResponse defines model for OTPLatestResponse.
type OTPLatestResponse struct {
	Code           string                  `json:"code"`
	MessageId      string                  `json:"message_id"`
	Source         OTPLatestResponseSource `json:"source"`
	VerificationId *string                 `json:"verification_id,omitempty"`
}

// OTPLatestResponseSource defines model for OTPLatestResponse.Source.
type OTPLatestResponseSource string

// Project defines model for Project.
type Project struct {
	CreatedAt *time.Time              `json:"created_at,omitempty"`
	Id        *string                 `json:"id,omitempty"`
	Name      *string                 `json:"name,omitempty"`
	Settings  *map[string]interface{} `json:"settings,omitempty"`
}

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	NextCursor *string    `json:"next_cursor,omitempty"`
	Projects   *[]Project `json:"projects,omitempty"`
}

// RequestLog defines model for RequestLog.
type RequestLog struct {
	Adapter        *string            `json:"adapter,omitempty"`
	CreatedAt      *time.Time         `json:"created_at,omitempty"`
	DurationMs     *int               `json:"duration_ms,omitempty"`
	Id             *string            `json:"id,omitempty"`
	Method         *string            `json:"method,omitempty"`
	Path           *string            `json:"path,omitempty"`
	ProjectId      *string            `json:"project_id,omitempty"`
	RequestBody    *string            `json:"request_body,omitempty"`
	RequestHeaders *map[string]string `json:"request_headers,omitempty"`
	ResponseBody   *string            `json:"response_body,omitempty"`
	ResponseStatus *int               `json:"response_status,omitempty"`
}

// RequestLogListResponse defines model for RequestLogListResponse.
type RequestLogListResponse struct {
	Logs       *[]RequestLog `json:"logs,omitempty"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// SendEmailRequest defines model for SendEmailRequest.
type SendEmailRequest struct {
	Attachments *[]AttachmentInput     `json:"attachments,omitempty"`
	Bcc         *[]openapi_types.Email `json:"bcc,omitempty"`
	CallbackUrl *string                `json:"callback_url,omitempty"`
	Cc          *[]openapi_types.Email `json:"cc,omitempty"`
	From        openapi_types.Email    `json:"from"`
	Html        *string                `json:"html,omitempty"`
	Subject     string                 `json:"subject"`
	Text        *string                `json:"text,omitempty"`
	To          []openapi_types.Email  `json:"to"`
}

// SendSMSRequest defines model for SendSMSRequest.
type SendSMSRequest struct {
	Body        string  `json:"body"`
	CallbackUrl *string `json:"callback_url,omitempty"`

	// From Sender ID (E.164 phone number or alphanumeric)
	From string            `json:"from"`
	To   SendSMSRequest_To `json:"to"`
}

// SendSMSRequestTo0 Single recipient
type SendSMSRequestTo0 = string

// SendSMSRequestTo1 Multiple recipients
type SendSMSRequestTo1 = []string

// SendSMSRequest_To defines model for SendSMSRequest.To.
type SendSMSRequest_To struct {
	union json.RawMessage
}

// StartVerificationRequest defines model for StartVerificationRequest.
type StartVerificationRequest struct {
	Channel     StartVerificationRequestChannel `json:"channel"`
	CodeLength  *int                            `json:"code_length,omitempty"`
	MaxAttempts *int                            `json:"max_attempts,omitempty"`

	// To Recipient (E.164 phone for SMS, email for email)
	To         string `json:"to"`
	TtlSeconds *int   `json:"ttl_seconds,omitempty"`
}

// StartVerificationRequestChannel defines model for StartVerificationRequest.Channel.
type StartVerificationRequestChannel string

// StatusEvent defines model for StatusEvent.
type StatusEvent struct {
	At        *time.Time         `json:"at,omitempty"`
	ErrorCode *string            `json:"error_code,omitempty"`
	Id        *string            `json:"id,omitempty"`
	MessageId *string            `json:"message_id,omitempty"`
	Status    *StatusEventStatus `json:"status,omitempty"`
}

// StatusEventStatus defines model for StatusEvent.Status.
type StatusEventStatus string

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name     *string                 `json:"name,omitempty"`
	Settings *map[string]interface{} `json:"settings,omitempty"`
}

// Verification defines model for Verification.
type Verification struct {
	Attempts    *int                 `json:"attempts,omitempty"`
	Channel     *VerificationChannel `json:"channel,omitempty"`
	Code        *string              `json:"code,omitempty"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	ExpiresAt   *time.Time           `json:"expires_at,omitempty"`
	Id          *string              `json:"id,omitempty"`
	MaxAttempts *int                 `json:"max_attempts,omitempty"`
	MessageId   *string              `json:"message_id,omitempty"`
	ProjectId   *string              `json:"project_id,omitempty"`
	Provider    *string              `json:"provider,omitempty"`
	ProviderRef *string              `json:"provider_ref,omitempty"`
	ServiceRef  *string              `json:"service_ref,omitempty"`
	Status      *VerificationStatus  `json:"status,omitempty"`
	To          *string              `json:"to,omitempty"`
}

// VerificationChannel defines model for Verification.Channel.
type VerificationChannel string

// VerificationStatus defines model for Verification.Status.
type VerificationStatus string

// VerificationListResponse defines model for VerificationListResponse.
type VerificationListResponse struct {
	NextCursor    *string         `json:"next_cursor,omitempty"`
	Verifications *[]Verification `json:"verifications,omitempty"`
}

// VerificationResponse defines model for VerificationResponse.
type VerificationResponse struct {
	Message      *Message      `json:"message,omitempty"`
	Verification *Verification `json:"verification,omitempty"`
}

// WebhookDelivery defines model for WebhookDelivery.
type WebhookDelivery struct {
	Attempt        *int                    `json:"attempt,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	Headers        *map[string]string      `json:"headers,omitempty"`
	Id             *string                 `json:"id,omitempty"`
	Kind           *WebhookDeliveryKind    `json:"kind,omitempty"`
	MessageId      *string                 `json:"message_id,omitempty"`
	NextRetryAt    *time.Time              `json:"next_retry_at,omitempty"`
	Payload        *map[string]interface{} `json:"payload,omitempty"`
	ProjectId      *string                 `json:"project_id,omitempty"`
	ResponseBody   *string                 `json:"response_body,omitempty"`
	ResponseStatus *int                    `json:"response_status,omitempty"`
	Status         *WebhookDeliveryStatus  `json:"status,omitempty"`
	Url            *string                 `json:"url,omitempty"`
	VerificationId *string                 `json:"verification_id,omitempty"`
}

// WebhookDeliveryKind defines model for WebhookDelivery.Kind.
type WebhookDeliveryKind string

// WebhookDeliveryStatus defines model for WebhookDelivery.Status.
type WebhookDeliveryStatus string

// WebhookDeliveryListResponse defines model for WebhookDeliveryListResponse.
type WebhookDeliveryListResponse struct {
	Deliveries *[]WebhookDelivery `json:"deliveries,omitempty"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// GetAttachmentParams defines parameters for GetAttachment.
type GetAttachmentParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetBatchParams defines parameters for GetBatch.
type GetBatchParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetLatestEmailParams defines parameters for GetLatestEmail.
type GetLatestEmailParams struct {
	To      string     `form:"to" json:"to"`
	Since   *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Project *string    `form:"project,omitempty" json:"project,omitempty"`
}

// SseEventsParams defines parameters for SseEvents.
type SseEventsParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// Healthz200JSONResponseBodyStatus defines parameters for Healthz.
type Healthz200JSONResponseBodyStatus string

// DeleteMessagesParams defines parameters for DeleteMessages.
type DeleteMessagesParams struct {
	Project string `form:"project" json:"project"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	Channel   *ListMessagesParamsChannel   `form:"channel,omitempty" json:"channel,omitempty"`
	To        *string                      `form:"to,omitempty" json:"to,omitempty"`
	From      *string                      `form:"from,omitempty" json:"from,omitempty"`
	Status    *ListMessagesParamsStatus    `form:"status,omitempty" json:"status,omitempty"`
	BatchId   *string                      `form:"batch_id,omitempty" json:"batch_id,omitempty"`
	Direction *ListMessagesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Since     *time.Time                   `form:"since,omitempty" json:"since,omitempty"`
	Limit     *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *string                      `form:"cursor,omitempty" json:"cursor,omitempty"`
	Project   *string                      `form:"project,omitempty" json:"project,omitempty"`
}

// ListMessagesParamsChannel defines parameters for ListMessages.
type ListMessagesParamsChannel string

// ListMessagesParamsStatus defines parameters for ListMessages.
type ListMessagesParamsStatus string

// ListMessagesParamsDirection defines parameters for ListMessages.
type ListMessagesParamsDirection string

// WaitForMessageParams defines parameters for WaitForMessage.
type WaitForMessageParams struct {
	To      *string                      `form:"to,omitempty" json:"to,omitempty"`
	Channel *WaitForMessageParamsChannel `form:"channel,omitempty" json:"channel,omitempty"`
	Since   *time.Time                   `form:"since,omitempty" json:"since,omitempty"`
	Timeout *int                         `form:"timeout,omitempty" json:"timeout,omitempty"`
	Project *string                      `form:"project,omitempty" json:"project,omitempty"`
}

// WaitForMessageParamsChannel defines parameters for WaitForMessage.
type WaitForMessageParamsChannel string

// GetMessageParams defines parameters for GetMessage.
type GetMessageParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetMessageRawParams defines parameters for GetMessageRaw.
type GetMessageRawParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetLatestOTPParams defines parameters for GetLatestOTP.
type GetLatestOTPParams struct {
	To      string     `form:"to" json:"to"`
	Since   *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Project *string    `form:"project,omitempty" json:"project,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListRequestLogsParams defines parameters for ListRequestLogs.
type ListRequestLogsParams struct {
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetRequestLogParams defines parameters for GetRequestLog.
type GetRequestLogParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// ListVerificationsParams defines parameters for ListVerifications.
type ListVerificationsParams struct {
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// GetVerificationParams defines parameters for GetVerification.
type GetVerificationParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// ListWebhooksParams defines parameters for ListWebhooks.
type ListWebhooksParams struct {
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// ReplayWebhookParams defines parameters for ReplayWebhook.
type ReplayWebhookParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// SendEmailJSONRequestBody defines body for SendEmail for application/json ContentType.
type SendEmailJSONRequestBody = SendEmailRequest

// SimulateInboundJSONRequestBody defines body for SimulateInbound for application/json ContentType.
type SimulateInboundJSONRequestBody = InboundRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// LinkCredentialJSONRequestBody defines body for LinkCredential for application/json ContentType.
type LinkCredentialJSONRequestBody = LinkCredentialRequest

// SendSMSJSONRequestBody defines body for SendSMS for application/json ContentType.
type SendSMSJSONRequestBody = SendSMSRequest

// StartVerificationJSONRequestBody defines body for StartVerification for application/json ContentType.
type StartVerificationJSONRequestBody = StartVerificationRequest

// CheckVerificationJSONRequestBody defines body for CheckVerification for application/json ContentType.
type CheckVerificationJSONRequestBody = CheckVerificationRequest

// AsSendSMSRequestTo0 returns the union data inside the SendSMSRequest_To as a SendSMSRequestTo0
func (t SendSMSRequest_To) AsSendSMSRequestTo0() (SendSMSRequestTo0, error) {
	var body SendSMSRequestTo0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSendSMSRequestTo0 overwrites any union data inside the SendSMSRequest_To as the provided SendSMSRequestTo0
func (t *SendSMSRequest_To) FromSendSMSRequestTo0(v SendSMSRequestTo0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSendSMSRequestTo0 performs a merge with any union data inside the SendSMSRequest_To, using the provided SendSMSRequestTo0
func (t *SendSMSRequest_To) MergeSendSMSRequestTo0(v SendSMSRequestTo0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSendSMSRequestTo1 returns the union data inside the SendSMSRequest_To as a SendSMSRequestTo1
func (t SendSMSRequest_To) AsSendSMSRequestTo1() (SendSMSRequestTo1, error) {
	var body SendSMSRequestTo1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSendSMSRequestTo1 overwrites any union data inside the SendSMSRequest_To as the provided SendSMSRequestTo1
func (t *SendSMSRequest_To) FromSendSMSRequestTo1(v SendSMSRequestTo1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSendSMSRequestTo1 performs a merge with any union data inside the SendSMSRequest_To, using the provided SendSMSRequestTo1
func (t *SendSMSRequest_To) MergeSendSMSRequestTo1(v SendSMSRequestTo1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SendSMSRequest_To) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SendSMSRequest_To) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAttachment Get attachment by ID
	// (GET /attachments/{id})
	GetAttachment(w http.ResponseWriter, r *http.Request, id string, params GetAttachmentParams)
	// GetBatch Get batch by ID
	// (GET /batches/{id})
	GetBatch(w http.ResponseWriter, r *http.Request, id string, params GetBatchParams)
	// SendEmail Send email
	// (POST /email)
	SendEmail(w http.ResponseWriter, r *http.Request)
	// GetLatestEmail Get latest email for a recipient
	// (GET /emails/latest)
	GetLatestEmail(w http.ResponseWriter, r *http.Request, params GetLatestEmailParams)
	// SseEvents Server-Sent Events stream
	// (GET /events)
	SseEvents(w http.ResponseWriter, r *http.Request, params SseEventsParams)
	// Healthz Readiness check
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// SimulateInbound Simulate inbound SMS
	// (POST /inbound)
	SimulateInbound(w http.ResponseWriter, r *http.Request)
	// DeleteMessages Delete all messages in project
	// (DELETE /messages)
	DeleteMessages(w http.ResponseWriter, r *http.Request, params DeleteMessagesParams)
	// ListMessages List messages
	// (GET /messages)
	ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams)
	// WaitForMessage Wait for message matching filters (long-poll)
	// (GET /messages/wait)
	WaitForMessage(w http.ResponseWriter, r *http.Request, params WaitForMessageParams)
	// GetMessage Get message by ID
	// (GET /messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id string, params GetMessageParams)
	// GetMessageRaw Get raw message (.eml for email)
	// (GET /messages/{id}/raw)
	GetMessageRaw(w http.ResponseWriter, r *http.Request, id string, params GetMessageRawParams)
	// GetLatestOTP Get latest OTP for a recipient
	// (GET /otp/latest)
	GetLatestOTP(w http.ResponseWriter, r *http.Request, params GetLatestOTPParams)
	// ListProjects List projects
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)
	// GetProject Get project by ID
	// (GET /projects/{id})
	GetProject(w http.ResponseWriter, r *http.Request, id string)
	// UpdateProject Update project
	// (PATCH /projects/{id})
	UpdateProject(w http.ResponseWriter, r *http.Request, id string)
	// LinkCredential Link credential to project
	// (POST /projects/{id}/credentials)
	LinkCredential(w http.ResponseWriter, r *http.Request, id string)
	// ListRequestLogs List request logs
	// (GET /requests)
	ListRequestLogs(w http.ResponseWriter, r *http.Request, params ListRequestLogsParams)
	// GetRequestLog Get request log by ID
	// (GET /requests/{id})
	GetRequestLog(w http.ResponseWriter, r *http.Request, id string, params GetRequestLogParams)
	// SendSMS Send SMS
	// (POST /sms)
	SendSMS(w http.ResponseWriter, r *http.Request)
	// ListVerifications List verifications
	// (GET /verifications)
	ListVerifications(w http.ResponseWriter, r *http.Request, params ListVerificationsParams)
	// StartVerification Start verification (OTP)
	// (POST /verifications)
	StartVerification(w http.ResponseWriter, r *http.Request)
	// GetVerification Get verification by ID
	// (GET /verifications/{id})
	GetVerification(w http.ResponseWriter, r *http.Request, id string, params GetVerificationParams)
	// CheckVerification Check verification code
	// (POST /verifications/{id}/check)
	CheckVerification(w http.ResponseWriter, r *http.Request, id string)
	// ExpireVerification Force verification expiry
	// (POST /verifications/{id}/expire)
	ExpireVerification(w http.ResponseWriter, r *http.Request, id string)
	// ListWebhooks List webhook deliveries
	// (GET /webhooks)
	ListWebhooks(w http.ResponseWriter, r *http.Request, params ListWebhooksParams)
	// ReplayWebhook Replay webhook delivery
	// (POST /webhooks/{id}/replay)
	ReplayWebhook(w http.ResponseWriter, r *http.Request, id string, params ReplayWebhookParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetAttachment Get attachment by ID
// (GET /attachments/{id})
func (_ Unimplemented) GetAttachment(w http.ResponseWriter, r *http.Request, id string, params GetAttachmentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetBatch Get batch by ID
// (GET /batches/{id})
func (_ Unimplemented) GetBatch(w http.ResponseWriter, r *http.Request, id string, params GetBatchParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SendEmail Send email
// (POST /email)
func (_ Unimplemented) SendEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLatestEmail Get latest email for a recipient
// (GET /emails/latest)
func (_ Unimplemented) GetLatestEmail(w http.ResponseWriter, r *http.Request, params GetLatestEmailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SseEvents Server-Sent Events stream
// (GET /events)
func (_ Unimplemented) SseEvents(w http.ResponseWriter, r *http.Request, params SseEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Healthz Readiness check
// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SimulateInbound Simulate inbound SMS
// (POST /inbound)
func (_ Unimplemented) SimulateInbound(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteMessages Delete all messages in project
// (DELETE /messages)
func (_ Unimplemented) DeleteMessages(w http.ResponseWriter, r *http.Request, params DeleteMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListMessages List messages
// (GET /messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WaitForMessage Wait for message matching filters (long-poll)
// (GET /messages/wait)
func (_ Unimplemented) WaitForMessage(w http.ResponseWriter, r *http.Request, params WaitForMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMessage Get message by ID
// (GET /messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id string, params GetMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMessageRaw Get raw message (.eml for email)
// (GET /messages/{id}/raw)
func (_ Unimplemented) GetMessageRaw(w http.ResponseWriter, r *http.Request, id string, params GetMessageRawParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLatestOTP Get latest OTP for a recipient
// (GET /otp/latest)
func (_ Unimplemented) GetLatestOTP(w http.ResponseWriter, r *http.Request, params GetLatestOTPParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListProjects List projects
// (GET /projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProject Get project by ID
// (GET /projects/{id})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateProject Update project
// (PATCH /projects/{id})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LinkCredential Link credential to project
// (POST /projects/{id}/credentials)
func (_ Unimplemented) LinkCredential(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRequestLogs List request logs
// (GET /requests)
func (_ Unimplemented) ListRequestLogs(w http.ResponseWriter, r *http.Request, params ListRequestLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRequestLog Get request log by ID
// (GET /requests/{id})
func (_ Unimplemented) GetRequestLog(w http.ResponseWriter, r *http.Request, id string, params GetRequestLogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SendSMS Send SMS
// (POST /sms)
func (_ Unimplemented) SendSMS(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVerifications List verifications
// (GET /verifications)
func (_ Unimplemented) ListVerifications(w http.ResponseWriter, r *http.Request, params ListVerificationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartVerification Start verification (OTP)
// (POST /verifications)
func (_ Unimplemented) StartVerification(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVerification Get verification by ID
// (GET /verifications/{id})
func (_ Unimplemented) GetVerification(w http.ResponseWriter, r *http.Request, id string, params GetVerificationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CheckVerification Check verification code
// (POST /verifications/{id}/check)
func (_ Unimplemented) CheckVerification(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExpireVerification Force verification expiry
// (POST /verifications/{id}/expire)
func (_ Unimplemented) ExpireVerification(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListWebhooks List webhook deliveries
// (GET /webhooks)
func (_ Unimplemented) ListWebhooks(w http.ResponseWriter, r *http.Request, params ListWebhooksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReplayWebhook Replay webhook delivery
// (POST /webhooks/{id}/replay)
func (_ Unimplemented) ReplayWebhook(w http.ResponseWriter, r *http.Request, id string, params ReplayWebhookParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAttachmentParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachment(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBatch operation middleware
func (siw *ServerInterfaceWrapper) GetBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBatchParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBatch(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendEmail operation middleware
func (siw *ServerInterfaceWrapper) SendEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestEmail operation middleware
func (siw *ServerInterfaceWrapper) GetLatestEmail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestEmailParams

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestEmail(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SseEvents operation middleware
func (siw *ServerInterfaceWrapper) SseEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SseEventsParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SseEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimulateInbound operation middleware
func (siw *ServerInterfaceWrapper) SimulateInbound(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimulateInbound(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMessages operation middleware
func (siw *ServerInterfaceWrapper) DeleteMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteMessagesParams

	// ------------- Required query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "channel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channel", r.URL.Query(), &params.Channel, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channel"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "batch_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "batch_id", r.URL.Query(), &params.BatchId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "batch_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "batch_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", r.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "direction"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WaitForMessage operation middleware
func (siw *ServerInterfaceWrapper) WaitForMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitForMessageParams

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channel", r.URL.Query(), &params.Channel, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channel"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "timeout" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeout", r.URL.Query(), &params.Timeout, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "timeout"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeout", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WaitForMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessageParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageRaw operation middleware
func (siw *ServerInterfaceWrapper) GetMessageRaw(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessageRawParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageRaw(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestOTP operation middleware
func (siw *ServerInterfaceWrapper) GetLatestOTP(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestOTPParams

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestOTP(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkCredential operation middleware
func (siw *ServerInterfaceWrapper) LinkCredential(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkCredential(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRequestLogs operation middleware
func (siw *ServerInterfaceWrapper) ListRequestLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRequestLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRequestLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRequestLog operation middleware
func (siw *ServerInterfaceWrapper) GetRequestLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRequestLogParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRequestLog(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendSMS operation middleware
func (siw *ServerInterfaceWrapper) SendSMS(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendSMS(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVerifications operation middleware
func (siw *ServerInterfaceWrapper) ListVerifications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVerificationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVerifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartVerification operation middleware
func (siw *ServerInterfaceWrapper) StartVerification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartVerification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVerification operation middleware
func (siw *ServerInterfaceWrapper) GetVerification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerificationParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVerification(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckVerification operation middleware
func (siw *ServerInterfaceWrapper) CheckVerification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckVerification(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExpireVerification operation middleware
func (siw *ServerInterfaceWrapper) ExpireVerification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExpireVerification(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhooks operation middleware
func (siw *ServerInterfaceWrapper) ListWebhooks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWebhooksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhooks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplayWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReplayWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "ulid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplayWebhookParams

	// ------------- Optional query parameter "project" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project", r.URL.Query(), &params.Project, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplayWebhook(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sms", wrapper.SendSMS)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/email", wrapper.SendEmail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/verifications", wrapper.ListVerifications)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/verifications", wrapper.StartVerification)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/verifications/{id}/check", wrapper.CheckVerification)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/verifications/{id}/expire", wrapper.ExpireVerification)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/verifications/{id}", wrapper.GetVerification)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/messages", wrapper.DeleteMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages/{id}/raw", wrapper.GetMessageRaw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages/wait", wrapper.WaitForMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/otp/latest", wrapper.GetLatestOTP)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/emails/latest", wrapper.GetLatestEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/inbound", wrapper.SimulateInbound)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/attachments/{id}", wrapper.GetAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/batches/{id}", wrapper.GetBatch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/requests", wrapper.ListRequestLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/requests/{id}", wrapper.GetRequestLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/webhooks", wrapper.ListWebhooks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/{id}/replay", wrapper.ReplayWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{id}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/projects/{id}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{id}/credentials", wrapper.LinkCredential)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.SseEvents)
	})

	return r
}
